// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"text/template"

	"github.com/mattermost/mattermost/server/public/model"
)

type roleEntry struct {
	Name        string
	Permissions string
}

var tmpl = template.Must(template.New("").Parse(`// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

// Code generated by generate_default_roles_permissions.go. DO NOT EDIT.

export const defaultRolesPermissions = {
{{- range .}}
    {{.Name}}: '{{.Permissions}}',
{{- end}}
};
`))

func main() {
	roles := model.MakeDefaultRoles()

	roleNames := make([]string, 0, len(roles))
	for name := range roles {
		roleNames = append(roleNames, name)
	}
	sort.Strings(roleNames)

	entries := make([]roleEntry, 0, len(roleNames))
	for _, name := range roleNames {
		perms := make([]string, len(roles[name].Permissions))
		copy(perms, roles[name].Permissions)
		sort.Strings(perms)
		entries = append(entries, roleEntry{
			Name:        name,
			Permissions: strings.Join(perms, " "),
		})
	}

	var b strings.Builder
	if err := tmpl.Execute(&b, entries); err != nil {
		fmt.Fprintf(os.Stderr, "error executing template: %v\n", err)
		os.Exit(1)
	}

	_, thisFile, _, _ := runtime.Caller(0)
	// This writes to: ../../../../webapp/platform/types/src/default_roles_permissions.js
	outPath := filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..", "webapp", "platform", "types", "src", "default_roles_permissions.js")

	if err := os.WriteFile(outPath, []byte(b.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", outPath, err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s\n", outPath)
}
